import csv
import json

STYLE_TRANSLATIONS = {
    "American-Style India Pale Ale": "美式印度淡色艾尔",
    "American-Style Pale Ale": "美式淡色艾尔",
    "Imperial or Double India Pale Ale": "帝国/双倍印度淡色艾尔",
    "French & Belgian-Style Saison": "法式与比利时式赛松",
    "American-Style Imperial Stout": "美式帝国司陶特",
    "Specialty Beer": "特种啤酒",
    "American-Style Amber/Red Ale": "美式琥珀/红艾尔",
    "Golden or Blonde Ale": "金色或金发艾尔",
    "American-Style Sour Ale": "美式酸艾尔",
    "American-Style Brown Ale": "美式棕色艾尔",
    "Brown Porter": "棕色波特",
    "American-Style Stout": "美式司陶特",
    "American-Style Lager": "美式拉格",
    "Belgian-Style White (or Wit) / Belgian-Style Wheat": "比利时白啤",
    "Fruit Beer": "果味啤酒",
    "Herb and Spice Beer": "草本与香料啤酒",
    "South German-Style Hefeweizen / Hefeweissbier": "南德式小麦啤",
    "Belgian-Style Tripel": "比利时三料",
    "Sweet or Cream Stout": "甜/奶油司陶特",
    "Light American Wheat Ale or Lager with Yeast": "美式轻小麦啤酒",
    "Wood- and Barrel-Aged Beer": "桶陈啤酒",
    "American-Style Barley Wine Ale": "美式大麦酒",
    "American-Style Pilsener": "美式皮尔森",
    "Berliner-Style Weisse (Wheat)": "柏林酸小麦",
    "American-Style Black Ale": "美式黑艾尔",
    "German-Style Pilsener": "德式皮尔森",
    "German-Style Kölsch / Köln-Style Kölsch": "科隆啤酒",
    "Juicy or Hazy India Pale Ale": "浑浊IPA",
    "Wood- and Barrel-Aged Sour Beer": "桶陈酸啤",
    "Robust Porter": "浓郁波特",
    "Other Belgian-Style Ales": "其他比利时式艾尔",
    "Oatmeal Stout": "燕麦司陶特",
    "Belgian-Style Blonde Ale": "比利时金发艾尔",
    "Irish-Style Red Ale": "爱尔兰红艾尔",
    "Belgian-Style Pale Ale": "比利时淡色艾尔",
    "Pumpkin Beer": "南瓜啤酒",
    "Session India Pale Ale": "会话IPA",
    "German-Style Märzen": "德式三月啤酒",
    "Belgian-Style Dark Strong Ale": "比利时深色烈性艾尔",
    "Specialty Stouts": "特种司陶特",
    "American-Style Cream Ale or Lager": "美式奶油艾尔",
    "Session Beer": "会话啤酒",
    "Contemporary Gose": "当代古斯",
    "Rye Ale or Lager with or without Yeast": "黑麦艾尔/拉格",
    "Strong Ale": "烈性艾尔",
    "American-Style Premium Lager": "美式高级拉格",
    "Extra Special Bitter": "特级苦啤",
    "Belgian-Style Dubbel": "比利时双料",
    "Imperial Red Ale": "帝国红艾尔",
    "German-Style Doppelbock": "德式双料博克",
    "Bohemian-Style Pilsener": "波西米亚皮尔森",
    "English-Style India Pale Ale": "英式印度淡色艾尔",
    "Scotch Ale": "苏格兰艾尔",
    "Fruit Cider": "果味苹果酒",
    "American-Style Light (Low Calorie) Lager": "美式轻拉格",
    "Ordinary Bitter": "普通苦啤",
    "Münchner (Munich)-Style Helles": "慕尼黑淡拉格",
    "Belgian-Style Quadrupel": "比利时四料",
    "Belgian-Style Pale Strong Ale": "比利时淡色烈性艾尔",
    "Vienna-Style Lager": "维也纳拉格",
    "Leipzig-Style Gose": "莱比锡古斯",
    "Bière de Garde": "法式窖藏艾尔",
    "English-Style Pale Mild Ale": "英式淡味软艾尔",
    "English-Style Brown Ale": "英式棕色艾尔",
    "German-Style Maibock / Helles Bock": "德式五月博克",
    "Juicy or Hazy Double India Pale Ale": "浑浊双倍IPA",
    "German-Style Dunkel Lager": "德式黑拉格",
    "Classic Australian-Style Pale Ale": "经典澳洲淡色艾尔",
    "American-Style Wheat Wine Ale": "美式小麦酒",
    "American-Style Imperial Porter": "美式帝国波特",
    "Best Bitter": "优质苦啤",
    "Cider": "苹果酒",
    "Open Category Mead": "开放类别蜂蜜酒",
    "Braggot": "布拉格特",
    "American-Style Dark Lager": "美式黑拉格",
    "Gluten-Free Beer": "无麸质啤酒",
    "Irish-Style Dry Stout": "爱尔兰干司陶特",
    "German-Style Eisbock": "德式冰博克",
    "English-Style Old Ale": "英式老艾尔",
    "Juicy or Hazy Triple India Pale Ale": "浑浊三倍IPA",
    "Smoke Beer": "烟熏啤酒",
    "German-Style Dunkelweizen": "德式黑小麦啤",
    "Dark Mead": "深色蜂蜜酒",
    "Classic English-Style Brown Ale": "经典英式棕色艾尔",
    "Traditional German-Style Bock": "传统德式博克",
    "Australian-Style Lager": "澳洲拉格",
    "American-Style Malt Liquor": "美式麦芽酒",
    "Traditional Style Mead": "传统风格蜂蜜酒",
    "English-Style Summer Ale": "英式夏日艾尔",
    "German-Style Rauchbier": "德式烟熏啤酒",
    "German-Style Schwarzbier": "德式黑啤",
    "American-Style Light Lager": "美式轻拉格",
    "Fruit Mead": "果味蜂蜜酒",
    "South German-Style Kristal Weizenbier": "南德水晶小麦啤",
    "Australian-Style Sparkling Ale": "澳洲气泡艾尔",
    "Baltic-Style Porter": "波罗的海波特",
    "Mead Melomel": "水果蜂蜜酒",
    "Metheglin": "香料蜂蜜酒",
    "German-Style Weizenbock": "德式小麦博克",
    "Pyment (Grape Melomel)": "葡萄蜂蜜酒",
    "American-Style Irish Red Ale": "美式爱尔兰红艾尔",
    "German-Style Altbier": "德式老啤酒",
    "Cyser": "苹果蜂蜜酒",
    "Japanese-Style Rice Lager": "日式米拉格",
    "Mead Other Fruit": "其他水果蜂蜜酒",
    "Historical Beer": "历史风格啤酒",
    "English-Style Dark Mild Ale": "英式深色软艾尔",
    "South German-Style Bernsteinfarbenes Weizenbier": "南德琥珀小麦啤",
    "Chili Pepper Beer": "辣椒啤酒",
    "Field Beer": "田园啤酒",
    "Mexican-Style Lager": "墨西哥拉格",
    "English-Style Barley Wine Ale": "英式大麦酒",
    "English-Style Imperial Stout": "英式帝国司陶特",
    "Belgian-Style Fruit Lambic": "比利时水果兰比克",
    "Mead Braggot": "麦芽蜂蜜酒",
    "Belgian-Style Oud Bruin": "比利时老棕啤",
    "English-Style Extra Special/Strong Bitter (ESB)": "英式特级苦啤",
    "Coffee Beer": "咖啡啤酒",
    "Belgian-Style Lambic": "比利时兰比克",
    "Perry": "梨酒",
    "Czech-Style Pilsener": "捷克皮尔森",
    "Australian-Style Style Pale Ale": "澳洲淡色艾尔",
    "Belgian-Style Gueuze": "比利时古斯",
    "German-Style Kellerbier": "德式窖藏鲜啤",
    "Low Alcohol Beer": "低酒精啤酒",
    "American-Style Wild Ale": "美式野生艾尔",
    "Fruit Perry": "果味梨酒",
    "Flavored Malt Beverage": "调味麦芽饮料",
    "Mead Show": "纯蜂蜜酒",
    "No Alcohol Beer": "无酒精啤酒",
    "Mead Dry": "干蜂蜜酒",
    "Sweet Cider": "甜苹果酒",
    "Mead Semi-Sweet": "半甜蜂蜜酒",
    "Mead Traditional": "传统蜂蜜酒",
    "Classic Irish-Style Dry Stout": "经典爱尔兰干司陶特",
    "Mead Cyser": "苹果蜂蜜酒",
    "Mead Pyment": "葡萄蜂蜜酒",
    "English-Style Oatmeal Stout": "英式燕麦司陶特",
    "Dry Cider": "干苹果酒",
    "Mead Melomel (Fruit Mead)": "水果蜂蜜酒",
    "Herb, Spice, or Vegetable Mead": "草本香料蜂蜜酒",
    "Mead Metheglin": "香料蜂蜜酒",
    "Mead Fruit": "果味蜂蜜酒",
    "Mead Herb": "草本蜂蜜酒",
    "English-Style Sweet Stout": "英式甜司陶特",
    "Mead Spiced": "香料蜂蜜酒",
    "Mead Dessert": "甜点蜂蜜酒",
    "Semi-Sweet Cider": "半甜苹果酒",
    "Mead Traditional": "传统蜂蜜酒",
    "English-Style Brown Porter": "英式棕色波特",
    "American-Style Sour Fruit Beer": "美式酸果啤",
    "Mead Specialty": "特种蜂蜜酒",
    "Special Cider or Perry": "特种苹果酒/梨酒",
    "Belgian-Style Faro": "比利时法罗啤酒",
    "New England Cider": "新英格兰苹果酒",
    "Common Cider": "普通苹果酒",
    "English-Style Porter": "英式波特",
    "Mead Hopped": "酒花蜂蜜酒",
    "Mead Oak-Aged": "橡木陈蜂蜜酒",
    "Cyser (Apple Melomel)": "苹果蜂蜜酒",
    "Mead Other Specialty": "其他特种蜂蜜酒",
    "Low Calorie Beer": "低卡啤酒",
    "Mead Sack": "高浓度蜂蜜酒",
    "English-Style Robust Porter": "英式浓郁波特",
    "Fruit Cyser": "果味苹果蜂蜜酒",
    "Mead Pyment": "葡萄蜂蜜酒",
    "Mead (Other Specialty)": "特种蜂蜜酒",
    "English-Style Stout": "英式司陶特",
    "Cider (Other Specialty)": "特种苹果酒",
    "Mead Fruit Melomel": "水果蜂蜜酒",
    "Cider Dry": "干苹果酒",
    "Mead Dessert Sack": "甜点蜂蜜酒",
    "Cider Sweet": "甜苹果酒",
    "Mead Semi-Sweet Traditional": "半甜传统蜂蜜酒",
    "Perry Dry": "干梨酒",
    "Perry Sweet": "甜梨酒",
}

CATEGORY_TRANSLATIONS = {
    "North American Origin Ales": "北美起源艾尔",
    "Hybrid/mixed Beer": "混合/特种啤酒",
    "Belgian And French Origin Ales": "比利时与法国起源艾尔",
    "British Origin Ales": "英国起源艾尔",
    "European-germanic Lager": "欧洲日耳曼式拉格",
    "North American Lager": "北美拉格",
    "German Origin Ales": "德国起源艾尔",
    "Mead, Cider, & Perry": "蜂蜜酒、苹果酒、梨酒",
    "Irish Origin Ales": "爱尔兰起源艾尔",
    "Other Lager": "其他拉格",
    "Malternative Beverages": "替代麦芽饮料",
    "International Styles": "国际风格",
    "International Ale Styles": "国际艾尔风格",
    "Other Origin": "其他起源",
}

STYLE_SHORT_DESCRIPTIONS = {
    "American IPA": "经典美式精酿，高酒花，柑橘/松木香气",
    "American Pale": "清爽易饮，中等酒花，美式IPA轻量版",
    "Imperial IPA": "IPA加强版，高酒精度，浓郁酒花",
    "Saison": "农舍艾尔，干爽微酸，酵母复杂度",
    "American Imperial Stout": "深色高酒精度，烘焙/巧克力风味",
    "Specialty": "使用不寻常原料的实验性啤酒",
    "Amber": "铜红色，中等麦芽与酒花平衡",
    "Blonde": "浅金色，清爽易饮，轻麦芽甜",
    "Sour": "自然发酵酸度，复杂风味",
    "American Brown": "深铜棕色，焦糖/巧克力麦芽",
    "Brown Porter": "英式深色，焦糖/巧克力风味",
    "American Stout": "黑色，烘焙咖啡/巧克力",
    "American Lager": "浅色清爽，玉米/大米辅料",
    "Witbier": "未发芽小麦，芫荽/橙皮香料",
    "Fruit Beer": "添加水果，果味与啤酒平衡",
    "Spice Beer": "草本/香料增味",
    "Hefeweizen": "香蕉/丁香酵母风味，云雾状",
    "Belgian Tripel": "金色高酒精度，复杂酯香",
    "Sweet Stout": "甜度高，可添加乳糖",
    "Wheat Ale": "含酵母，云雾状，低酒精度",
    "BBL Aged": "木桶陈化，增加复杂度",
    "American Barleywine": "高酒精度，浓郁麦芽",
    "American Pilsener": "中等酒花，玉米/大米辅料",
    "Berlinerweisse": "低酒精度，高酸度",
    "Black Ale": "深色但不厚重，烘焙与酒花平衡",
    "German Pilsener": "经典德国拉格，贵族酒花",
    "Kölsch": "科隆特产，清爽，艾尔发酵",
    "Juicy or Hazy IPA": "新英格兰风格，云雾状，果汁感",
    "BBL Aged Sour": "木桶陈化的酸啤酒",
    "Robust Porter": "更深色，更浓郁烘焙",
    "Belgian Ale": "其他比利时传统风格",
    "Oatmeal Stout": "添加燕麦，口感顺滑",
    "Belgian Blonde": "金色，中等酒精度，酵母酯香",
    "Irish Red": "红铜色，焦糖麦芽甜",
    "Belgian Pale": "琥珀色，酵母与酒花平衡",
    "Pumpkin Beer": "秋季特色，南瓜/香料",
    "Session IPA": "低酒精度保留IPA风味",
    "Märzen": "慕尼黑啤酒节，麦芽香甜",
    "Belgian Dark Strong": "深色高酒精度，复杂麦芽",
    "Stout": "特种司陶特",
    "Cream Ale": "艾尔发酵拉格陈化，清爽",
    "Session": "低酒精度，易饮",
    "Contemporary Gose": "现代风格酸小麦啤",
    "Rye Ale": "黑麦麦芽酿造",
    "Strong Ale": "英国传统高酒精度",
    "American Premium Lager": "麦芽味更重的美式拉格",
    "ESB": "英式苦啤加强版",
    "Belgian Dubbel": "红棕色，麦芽甜香",
    "Imperial Red": "红色高酒精度，麦芽酒花平衡",
    "Doppelbock": "德国烈性拉格，麦芽香甜",
    "Bohemian Pilsener": "捷克皮尔森，麦芽与酒花平衡",
    "English IPA": "英式IPA，泥土/草本酒花",
    "Scotch Ale": "苏格兰风格，浓郁麦芽甜",
    "Fruit Cider": "果味苹果酒",
    "American Light Lager": "极低卡路里，极清爽",
    "Bitter": "英式苦啤基础款",
    "Helles": "慕尼黑淡拉格，麦芽香甜",
    "Belgian Quad": "比利时四料，极高酒精度",
    "Belgian Pale Strong": "金色烈性，轻盈酒体",
    "Vienna Lager": "铜红色，麦芽香甜",
}

def translate_style(name):
    return STYLE_TRANSLATIONS.get(name, name)

def translate_category(name):
    return CATEGORY_TRANSLATIONS.get(name, name)

def get_short_desc(short_name, full_name):
    if short_name and short_name in STYLE_SHORT_DESCRIPTIONS:
        return STYLE_SHORT_DESCRIPTIONS.get(short_name, "")
    for key in STYLE_SHORT_DESCRIPTIONS:
        if key in short_name or key in full_name:
            return STYLE_SHORT_DESCRIPTIONS[key]
    return ""

def main():
    rows = []
    with open('beer_styles.csv', 'r', encoding='utf-8-sig') as f:
        reader = csv.DictReader(f)
        for row in reader:
            rows.append(row)
    
    fieldnames = [
        '排名', '风格ID', '英文风格名', '中文风格名',
        '类别ID', '英文类别名', '中文类别名',
        '数据量', 'IBU最小值', 'IBU最大值', 'ABV最小值', 'ABV最大值',
        'SRM最小值', 'SRM最大值', '风格简介', '英文详细描述'
    ]
    
    with open('beer_styles_中文完整表.csv', 'w', newline='', encoding='utf-8-sig') as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        
        for idx, row in enumerate(rows, 1):
            short_name = row.get('style_short_name', '')
            full_name = row.get('style_name', '')
            writer.writerow({
                '排名': idx,
                '风格ID': row.get('style_id', ''),
                '英文风格名': row.get('style_name', ''),
                '中文风格名': translate_style(row.get('style_name', '')),
                '类别ID': row.get('category_id', ''),
                '英文类别名': row.get('category_name', ''),
                '中文类别名': translate_category(row.get('category_name', '')),
                '数据量': row.get('count', ''),
                'IBU最小值': row.get('ibu_min', ''),
                'IBU最大值': row.get('ibu_max', ''),
                'ABV最小值': row.get('abv_min', ''),
                'ABV最大值': row.get('abv_max', ''),
                'SRM最小值': row.get('srm_min', ''),
                'SRM最大值': row.get('srm_max', ''),
                '风格简介': get_short_desc(short_name, full_name),
                '英文详细描述': row.get('style_description', ''),
            })
    
    print(f"已生成包含汉译的完整表格文件: beer_styles_中文完整表.csv")
    print(f"共 {len(rows)} 条啤酒风格记录")

if __name__ == "__main__":
    main()
